apiVersion: v1
kind: Service
metadata:
  name: php-fpm-prometheus-exporter
  labels:
    app: php-fpm-prom-exporter
spec:
  type: NodePort
  ports:
    - port: 9253
      targetPort: 9253
      protocol: TCP
      name: http-web
  selector:
    app.kubernetes.io/name: test-app